### ISSUE TITLE
Wrong type for next state tuple field access

### ISSUE THREAD

**Issue by mohammadfawaz** [essential-contributions/pint#1014]
Example:
```rust
storage {
    t: {int, int},
}

predicate foo() {
    let t = storage::t;
    constraint t.0' == 0;
}
```
This compiles to:
```rust
storage {
    t: {int, int},
}

predicate ::foo(
) {
    let ::t: {int, int} = __storage_get({0, 0});
    constraint (::t'.0 == 0);
    constraint __eq_set(__mut_keys(), {0});
}
```
but then we think the type of `::t'` is `int`. This does not happen if we write `constraint t'.0 == 0` in the original code.

**Comment by otrho** [comment]
What is the error here?  `t'` is a tuple and `t.0'` and `t'.0` are ints, no?  What's the actual difference between `t'.0` and `t.0'` in the source?

**Comment by mohammadfawaz** [comment]
Oh sorry should've been clearer. This currently errors out with
```console
Error: compiler internal error: type must exist and be a tuple type
Error: compiler internal error: predicate must exist in the compiled_predicates map
```
After a quick investigation, it seems that the type of `t` itself in `t.0'` is `int` instead of `{int, int}`.

To your comment, `t.0'` and `t'.0` should be exactly the same :)
