### ISSUE TITLE
Array scalarisation should be able to handle dependencies.

### ISSUE THREAD

**Issue by otrho** [essential-contributions/pint#515]
This should be compiled OK IMO, if `ary_i` is scalarised first, then `ary_a`.
```
let ary_a = [true, false];
let ary_i = [1, 0];

let x: bool;

constraint x == ary_a[ary_i[0]] && x != ary_a[ary_i[1]];

solve satisfy;
```
But instead scalarisation fails since `ary_i[0]` is still an `ArrayElementAccess` when trying to evaluate the index for `ary_a[ary_i[0]]`.
```
Error: compiler internal error: unexpected expression during compile-time evaluation
Error: attempt to use a non-constant value as an array index
   ╭─[foo.yrt:6:23]
   │
 6 │ constraint x == ary_a[ary_i[0]] && x != ary_a[ary_i[1]];
   │                       ────┬───
   │                           ╰───── this must be a constant
───╯

```
I'm wondering though if I'm off the mark, since trying to force `ary_i` to be scalarised first by either re-ordering the declarations in source or by renaming it to be lexicographically later doesn't work.  It iterates through `var_types` so I would've thought one of those approaches would work.  :thinking:

**Comment by mohammadfawaz** [comment]
I'm closing this now since scalarization has been removed.
