### ISSUE TITLE
Sanitize `ArrayElementAccess` in `IntermediateIntent`

### ISSUE THREAD

**Issue by lethalgem** [essential-contributions/pint#533]
Many tests are leaving `ArrayElementAccess` in the `final intermediate intent`. Although the `final ii` is solvable, not all `ArrayElementAccess`s are being removed.

Likely related to #528, though not confirmed yet

For example: `non_const_index.yrt` fails with 

```zsh
...
compiler internal error: array element access present in final intent exprs slotmap
@40..44: array element access present in final intent exprs slotmap
```

The test is below.

```yrt
let n: int;
let a: int[10];

constraint a[n] == 3;

solve satisfy;
```

**Comment by mohammadfawaz** [comment]
This is fine now since the asm gen does support array accesses.
