### ISSUE TITLE
Allow `Map` to be declared outside of `Storage Block`

### ISSUE THREAD

**Issue by lethalgem** [essential-contributions/pint#574]
Currently the `parser` only allows `map` declarations inside of `storage blocks`. We want to allow a `map` to be declared earlier then used in the storage block.

Ex.
```pnt
type myMap = (b256 => int);

results in

Error: expected `::`, `b256_ty`, `bool_ty`, `ident`, `int_ty`, `real_ty`, `string_ty`, or `{`, found `(`
    ╭─[test.pnt:17:14]
    │
 17 │ type myMap = (b256 => int);
    │              ┬  
    │              ╰── expected `::`, `b256_ty`, `bool_ty`, `ident`, `int_ty`, `real_ty`, `string_ty`, or `{`
────╯

----


Vs. a storage block has no issues

storage {
    balances: (b256 => int),
}

```

**Comment by lethalgem** [comment]
@otrho 

Pretty much wrapped on this issue with branch `ian/574`. I've just got one use case that's been plaguing me.

I believe we want this to compile? Because we want to be able to declare map types outside of storage.

```pnt
storage {
    m: MyMap,
    n: MyInt,
    o: MyNestMap,
}

predicate test {
    type MyMap = (int => int);
    type MyInt = int;
    type MyNestMap = (MyInt => int);
}
```

Although it doesn't make too much sense, as a user could easily just add another `predicate` that would overwrite the definitions...

ex.
```pnt
predicate new_test {
    type MyMap = (bool => bool);
    type MyInt = int;
    type MyNestMap = (MyInt => int);
}
```

Either way, the issue I'm running into is that we type check the `storage block` which doesn't have access to the type definitions for `MyMap`, `MyInt`, `MyNestMap`. So the the `NewTypeDecls` aren't used to lower what is in the `storage block`. Then we error out with:

```pnt
Error: compiler internal error: only ints, bools, and maps are currently allowed in a storage block
     ╭─[test.pnt:107:5]
     │
 107 │     m: MyMap,
     │     ────┬───  
     │         ╰───── only ints, bools, and maps are currently allowed in a storage block
─────╯
Error: compiler internal error: only ints, bools, and maps are currently allowed in a storage block
     ╭─[test.pnt:108:5]
     │
 108 │     n: MyInt,
     │     ────┬───  
     │         ╰───── only ints, bools, and maps are currently allowed in a storage block
─────╯
Error: compiler internal error: only ints, bools, and maps are currently allowed in a storage block
     ╭─[test.pnt:109:5]
     │
 109 │     o: MyNestMap,
     │     ──────┬─────  
     │           ╰─────── only ints, bools, and maps are currently allowed in a storage block
```

I could easily allow `custom types` inside of `storage blocks` but that wouldn't really solve the core problem.

FWIW, before pulling in the changes made to `master`, I was testing and passing:

```pnt
predicate test {
    type MyMap = (int => int);
    type MyInt = int;
    type MyNestMap = (MyInt => int);

    storage {
        m: MyMap,
        n: MyInt,
        o: MyNestMap,
    }
}
```

which is no longer allowed

**Comment by otrho** [comment]
Yep, the changes around scoping for different elements is kinda ongoing.  We originally had a single module, which was the root predicate and contained everything.  Then we added sub-predicates and then later removed the root predicate, so the compiler code doesn't properly reflect how the language now works.

It's broken a couple of things, I'm currently working on #774 to fix some of it.  But we need to decide a couple more things for scoping type aliases.

I think that the types used in storage blocks should be only declared at the root level.  So in this change you wouldn't have to do anything too tricky -- the only types allowed in storage are in the root predicate.

The next question is do we even allow `type` decls inside predicate blocks?  Perhaps all type aliases should be global.  And the if we do allow them in predicates, I would assume they're only available to expressions in that predicate, and having different types with the same name, but in different predicates would be allowed.  This could be both confusing and useful.  Confusing for someone reading the code and mistaking one type for the other.  But useful for certain types that are used similarly for different predicates, a bit like generics.

Personally I think it'd be simpler and cleaner to only allow `type` decls at the top level, without losing too much expressivity.
