### ISSUE TITLE
Compilation needs to output a 'solver ABI'.

### ISSUE THREAD

**Issue by otrho** [essential-contributions/pint#609]
In the simplest of cases the compiler will map `let` variable declarations directly to the VM decision variable slots.

This is complicated by types with sizes larger than 1 word like `b256` which use 4 slots.

It is complicated even further by dynamically sized arrays where determining the slot for a decision variable isn't known at compile time.  The indexing logic becomes much harder to reason about from the VM constraint opcodes.

On top of this the compiler may choose to re-order variable declarations for better efficiency, and may choose to remove or add decision variables as needed -- some `let` decls may not need a slot at all if they're consts, and sometimes the compiler may choose to create intermediate variables/slots (and related constraints) to resolve dependencies between other vars.

It will be important for the compiler to emit some sort of mapping between how it has decided to map out the slots as used by constraints and their equivalent declarations in source.  This will probably also be necessary for state slots.

It's not unlike debug symbol information for other compilers -- letting tooling understand how to symbolically access and/or manipulate VM slots consistently.

**Comment by mohammadfawaz** [comment]
I'm closing this since it's basically done.
