### ISSUE TITLE
Update The Pint Book to focus on `pint` as main CLI

### ISSUE THREAD

**Issue by mitchmindtree** [essential-contributions/pint#687]
This totally slipped my mind while finishing up #659, but I'm realising I should have also updated the book for this?

Perhaps we can still mention `pintc` and that it's available as a more minimal tool, but that most package creation, building and management should happen via `pint`?

We'll probably also want:

- A manifest reference, covering all fields in the manifest.
- A command reference (generated via `pint --help`?

cc @mohammadfawaz might have some thoughts on how this should be structured?

**Comment by mohammadfawaz** [comment]
I think this is pretty much done.
