### ISSUE TITLE
Only generate `.json` output on successful compile.

### ISSUE THREAD

**Issue by otrho** [essential-contributions/pint#704]
The current `master` will drop the ABI JSON file even if the compile fails, which might be fine but feels weird to me.

**Comment by lethalgem** [comment]
Note to self: Double check if we are emitting JSON when we run just `pint build`

**Comment by lethalgem** [comment]
@otrho Is this still an issue? I'm unable to reproduce it.

When I run my own `test.pnt` file with `cargo run --bin pintc test.pnt` I do not get any ABI JSON file or other JSON files.
```pnt
ex. 
predicate test {
    var x = 2;
    var y: ( int => int );
}

results in 

Error: variables cannot have storage map type
   ╭─[test.pnt:3:9]
   │
 3 │     var y: ( int => int );
   │         ┬  
   │         ╰── found variable of type storage map here
───╯
Error: could not compile `test.pnt` due to previous error
```

When I try with the latest `pint toolchain` using `pint build` I also do not get any JSON files in the `/out` directory
```pnt
ex. 
storage {
    counter: int,
}

predicate Increment {
    state counter: int = storage::counter;

    constraint (counter == nil && counter' == 1) || counter' == counter + 1;

    var x: (int => int);
}

results in

   Compiling counter [contract] ...
Error: expected `::`, `a type`, `an identifier`, or `{`, found `(`
    ╭─...
    │
 10 │     var x: (int => int);
    │            ┬  
    │            ╰── expected `::`, `a type`, `an identifier`, or `{`
────╯
Error: `pintc` encountered an error: parse error
```

This is for both parsing and flattening compilation errors.

Please let me know if I'm missing something key here 😄

**Comment by otrho** [comment]
Yeah, if you take a look in `main.rs` the steps we take are lex+parse, followed by type-check & flatten, then to write the ABI, then to compile the contract.  So if there's any error during asm-gen then it'll have written the abi but still report an error (probably an `InternalError`).

Here's a contrived example:
```
predicate test {
    state x = __storage_get(123);
}
```
This was annoying me when using tests which might (deliberately) fail during asm-gen and I'd use `cargo r` on the test file to confirm the error messages looked correct before putting them into the test file for `cargo t` and a `.json` file would get dropped, which the test harness now checks against.  So you get a weird error from `cargo t` until you realise you need to delete the ABI file.

So it's not high priority but it was annoying.  The answer I think is to put all the `.json` dropping code together in `main.rs` after we've successfully built everything.

**Comment by lethalgem** [comment]
Ah I see. The issue is happening from the compile failing during the asm-gen and not from parsing and flattening issues.
