### ISSUE TITLE
Remove the `key` field from `KeyedTypeABI::Tuple` and `KeyedTypeABI::Map`

### ISSUE THREAD

**Issue by mohammadfawaz** [essential-contributions/pint#752]
They are not necessary. Only primitive types should get keys... All other keys can be inferred from them.

**Comment by mitchmindtree** [comment]
@mohammadfawaz are arrays of tuples also flattened? E.g. 

```
storage {
    foo: { int, int }[3],
}
```
for each element, does this result in the following keys:

- [0]
- [1]
- [2]
- [3]
- [4]
- [5]

or these:

- [0, 0]
- [0, 1]
- [1, 0]
- [1, 1]
- [2, 0]
- [2, 1]

And is the behaviour the same for a tuple of arrays? E.g. `{ int[2], int[2], int[2] }`.

just checking as this does complicate abi-gen key construction a bit further still, but might be doable... will report back.

**Comment by mohammadfawaz** [comment]
Yup! Arrays of tuples are flattened all the way.

**Comment by mitchmindtree** [comment]
> Yup! Arrays of tuples are flattened all the way.

And just double-checking, is the case the same for tuples containing arrays?

**Comment by mohammadfawaz** [comment]
> > Yup! Arrays of tuples are flattened all the way.
> 
> 
> 
> And just double-checking, is the case the same for tuples containing arrays?

Absolutely. We think of everything as a pile of data, except for maps, and likely other dynamic containers in the future.

**Comment by mitchmindtree** [comment]
Closed via #779.
