### ISSUE TITLE
Allow accessing storage maps in tuples

### ISSUE THREAD

**Issue by mohammadfawaz** [essential-contributions/pint#808]
The following should work but doesn't:
```rust
storage {
    t: { ( int => int ), int },
}

predicate test {
    state t = storage::t.0[0];
}
```
Error:
```console
❯ pintc test.pnt
Error: expected `.`, or `;`, found `[`
   ╭─[test.pnt:6:27]
   │
 6 │     state t = storage::t.0[0];
   │                           ┬
   │                           ╰── expected `.`, or `;`
───╯
Error: could not compile `test.pnt` due to previous error
```

**Comment by mohammadfawaz** [comment]
@lethalgem can you double check that this works now and if so, please add an elaborate test under `validate_tests`?

**Comment by lethalgem** [comment]
@mohammadfawaz I can confirm this does work. Adding tests now

**Comment by lethalgem** [comment]
I'm stuck on determining the proper keys for the test. I've taken a look at `tests/validation_tests/storage_array.pnt`, `tests/validation_tests/storage_map.pnt`, and `tests/validation_tests/transient_local.toml` to try and garner what the appropriate keys should be.

```
looking at tests/validation_tests/storage_map.pnt I believe the following should be a valid way of assigning values to the map

storage {
    t: { ( int => int ), int },
}

predicate Test() {
    state t = mut storage::t.0[0];
    constraint t' == 1;
}

here are the keys I've put in the .toml

[[data]]
predicate_to_solve = { predicate = "::Test" }
state_mutations = [
  { key = [0, 0], value = [1] },         # storage::t
]
```

When I run the test I get this error
```
Error submitting solution: constraint checking failed: check failed: errors occurred while executing one or more constraints: the constraints at the following indices failed: 
  0: operation at index 4 failed: access operation error: state value_ix out of bounds: 0..1
```

I've searched the repo and I can't find this error message, so I'm guessing it's not coming from Pint. I'm not sure where I'm violating bounds, but it's obvious enough that I'm doing something wrong in my .pnt file.

Any assistance is appreciated! :D @mohammadfawaz @otrho

**Comment by mohammadfawaz** [comment]
In addition to adding a test in `validation_tests`, you should also add a test to `pint-abi-gen-tests`. You can update `simple` if you like or add your own. Basically, we want to make sure that specifying state mutations in Rust using abi gen works for complex types like `{ ( int => int ), int }`
