### ISSUE TITLE
Declaring a `custom type` in the `storage block` should error

### ISSUE THREAD

**Issue by lethalgem** [essential-contributions/pint#814]
> Should this be allowed / should this be a separate issue?
> 
> ```
> storage {
>     x: ( int => int ),
>     t: { x, int },
> }
> 
> predicate test {
>     state t = storage::t;
> }
> ```
> 
> We do not report any compilation arrows for the above. `::x` is not considered a `new type decl,` but is considered to be a `custom` type. So when checking for a map it fails. Though I think this should be a syntactic error because `::x` should be accessed as `storage::x` which isn't allowed inside of `storage{}`

Yeah this should fail somewhere else because `x` is not a type. What you're trying to do shouldn't work because `x` is a storage variable while `{ x, int }` is a type.

_Originally posted by @mohammadfawaz in https://github.com/essential-contributions/pint/issues/813#issuecomment-2263617754_

**Comment by otrho** [comment]
I am doing work right now which I think would address this.
