### ISSUE TITLE
Do not compile dead state declarations

### ISSUE THREAD

**Issue by mohammadfawaz** [essential-contributions/pint#815]
For example:
```rust
storage {
    x: int,
}

predicate Test {
    state x = storage::x;
}
```
`state x` is not used anywhere in the predicate so the compiler can just skip it completely when generating assembly. That being said, if the declaration had `mut` in it: `state x = mut storage::x`, then mutability should still be taken into account (i.e. should still generate a `__mut_keys_contains` constraint)

**Comment by lethalgem** [comment]
Note to self: 
- new pass for semantic analysis
- go through all the state exprs and see if they're used
- mark dead ones
- remove the dead ones in a separate loop after (you can change items with a mutable iterator, but not remove elements of the vector)
