### ISSUE TITLE
Remove dead constraints

### ISSUE THREAD

**Issue by mohammadfawaz** [essential-contributions/pint#834]
For example, remove constraints like this:
```
constraint true;
constraint !false;
constraint 1 == 1;
constraint x == x;
```
and so on...

We can start with some simple stuff and evolve the pass to support more complex structures in the future.

**Comment by mohammadfawaz** [comment]
The function [`evaluate`](https://github.com/essential-contributions/pint/blob/80ab3987c8bf256a4f4e9fec5d9a1979b2020ca5/pintc/src/expr/evaluate.rs#L60) should be quite useful here.

**Comment by otrho** [comment]
I think the E2E tests should have another phase which includes these type of transforms separately.

- parsed / parse_failure
- typecheck_failuire
- flattened
- optimised

Where 'flattened' is anything which is desugared but still pretty much resembles the parsed tree.  The 'optimised' stage will have items removed or combined and is the final output.

**Comment by mohammadfawaz** [comment]
Yes that makes sense. I had a chat with @lethalgem yesterday about the differences between "flattening" (we may need a better name for this now) and "optimization" and how one is required while the other is not. We should certainly split the two into separate phases where flattening happens first and produces valid code that asm gen can understand, while the optimizers runs after (and is optional in principle). Things like dead code elimination and const folding should go into the optimizer.
