### ISSUE TITLE
`in` expressions in `const` initializers 

### ISSUE THREAD

**Issue by mohammadfawaz** [essential-contributions/pint#886]
Low priority but the following should really work:
```rust
const x = 1 in 1..2;
```
and so is
```rust
const x = 1 in [1, 2];
```
Currently, we just get an internal error:
```console
Error: compiler internal error: unexpected expression during compile-time evaluation
```

**Comment by otrho** [comment]
These are the expressions we don't/can't evaluate at the moment.   Of these perhaps the `In`, `Generator`, `Match` and all 3 'union' expressions could be supported to some degree.  A problem is they need to evaluate to an immediate, so `Range` and `Generator` could be evaluated but only in conjunction with other expressions.

E.g., `1 in 1..2` is evaluating an `In` and `Range` but results in an immediate bool, so it works.  But the intermediate value for the range isn't an immediate so it doesn't fit our current code.  A solution might be to use a different type for `evaluate()`, a special evaluated immediate, which is translated to a Pint immediate in the end, if possible.

```
     Expr::Error(_)
     | Expr::StorageAccess { .. }
     | Expr::ExternalStorageAccess { .. }
     | Expr::MacroCall { .. }
     | Expr::IntrinsicCall { .. }
     | Expr::In { .. }
     | Expr::Range { .. }
     | Expr::Generator { .. }
     | Expr::Match { .. }
     | Expr::UnionVariant { .. }
     // These union exprs can unpack if their expression is a UnionVariant literal.
     | Expr::UnionTagIs { .. } | Expr::UnionValue { .. } => {
         Err(handler.emit_err(Error::Compile {
             error: CompileError::Internal {
                 msg: "unexpected expression during compile-time evaluation",
                 span: empty_span(),
             },
         }))
     }
```
