### ISSUE TITLE
type check before evaluating `consts`

### ISSUE THREAD

**Issue by lethalgem** [essential-contributions/pint#913]
`const f = true in 3..2` will make it to the evaluation stage even though it _should_ result in 

```
Error: value type and array element type in range differ
   ╭─[test.pnt:7:22]
   │
 7 │     const f = true in [1, 2];
   │                        ┬
   │                        ╰── array element type mismatch; expecting `bool` type, found `int` type
───╯
```

> ...
> A user can still write `const f = true in 3..2;` without an error occurring before this stage.
> 
> FWIW, if it is _not_ a `const` then we type check the range. Ex.
> ```
> predicate Test {
>     var l = true in 1..2;
> }
> 
> Error: value type and range type differ
>     ╭─[test.pnt:18:21]
>     │
>  18 │     var l = true in 1..2;
>     │                     ┬
>     │                     ╰── range type mismatch; expecting `bool` type, found `int` type
> ────╯
> ```
>
> _Originally posted by @lethalgem in https://github.com/essential-contributions/pint/pull/911#discussion_r1790795496_

**Comment by otrho** [comment]
WTF?  Are we not type checking `const` initialisers?

**Comment by mohammadfawaz** [comment]
Haha yes we evaluate constants before type checking exprs.
