### ISSUE TITLE
Allow solution generation from Pint

### ISSUE THREAD

**Issue by mohammadfawaz** [essential-contributions/pint#984]
This is related to unit testing in pint but we would have a separate commands that just generates a solution object (and its JSON representation) via something like `pint generate-solution` or something.

**Comment by mitchmindtree** [comment]
This could potentially be done as a new "package" kind at the manifest level too.

E.g. currently we have "library" and "contract" package kinds, where `library`s are collections of items, and `contract`s compile to a contract `<name>.json`. Perhaps we could add a "solution" kind that, when built with `pint build`, generates a solution JSON? Something like:

| Package Kind | `pint build` output in `out/<profile>/` |
| --- | --- |
| `library` | type-checks |
| `contract` | `<name>-contract.json`, `<name>-contract-abi.json` |
| `solution` | `<name>-solution.json` |

**Comment by mohammadfawaz** [comment]
Dup of https://github.com/essential-contributions/pint/issues/598. Closing this one and copying over all the information here.
